services:
  crypto_collector:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
 